apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined
  ports:
    - name: backend-port  
      protocol: TCP
      port: 5000          
      targetPort: 5000    
    - name: frontend-port 
      protocol: TCP
      port: 5001          
      targetPort: 5001    
  type: NodePort      
