apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: 2024cmpe492/frontend:latest
        ports:
        - containerPort: 5001
        env:
        - name: BACKEND_URL
          value: "http://backend-service"
        resources:
          requests:
            cpu: "100m"       
            memory: "256Mi"   
          limits:
            cpu: "200m"       
            memory: "512Mi"   
