apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-apache
  template:
    metadata:
      labels:
        app: web-server-apache
    spec:
      containers:
        - name: web-server-apache
          image: web-server-apache:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8061
          resources:
            requests:
              memory: "64Mi"
              cpu: "1000m"
